FROM ubuntu:18.04

RUN apt-get update && apt-get install -y openssh-server

RUN mkdir /var/run/sshd

ENV ROOT_PASSWORD = "ubuntu"
ENV USER_NAME = "chibutsu"
ENV USER_PASSWORD = "chibutsu"
RUN echo root:${ROOT_PASSWORD} | chpasswd
RUN echo ${USER_NAME}:${USER_PASSWORD} | chpasswd

# RUN sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd

ENV NOTVISIBLE "in users profile"
RUN echo "export VISIBLE=now" >> /etc/profile

EXPOSE 22

CMD ["/usr/sbin/sshd", "-D"]

